name: CI/CD for Docker

on:
  push:
    branches:
      - main         
    tags:
      - v*           

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23'  

      - name: Install dependencies
        run: go mod tidy
        
      - name: Run tests
        run: go test ./...

  publish:
    runs-on: ubuntu-latest
    needs: test                  
    if: startsWith(github.ref, 'refs/tags/')  
    steps:
      - name: Checkout code
        uses: actions/checkout@v1.3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  
          password: ${{ secrets.DOCKER_PASSWORD }}  
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v1.3
        with:
          context: .                     
          push: true                     
          tags: NickLand74/final-task:${{ github.ref_name }}  
